data:
  data_seed: 155
  dataset: clustervec_fine_tune
  image_folder: split_ls/
  normalize: true
  num_classes: 5
  root_path: /scratch2/clear/larbez/Workspace/datasets/Prioritaires_cropped/
  subset_path: PRIO_subsets/
  unlabeled_frac: 0.97
logging:
  folder: /scratch2/clear/larbez/Workspace/PAWS/Prio_ft_really_from_scratch_3percent/
  pretrain_path: /scratch2/clear/larbez/Workspace/PAWS/Prio_from_scratch_really_3percent_predhead/paws-best.pth.tar
  write_tag: paws-latest
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  master_port: 4029
  model_name: resnet50
  training: true
  use_fp16: false
optimization:
  epochs: 100
  lr: 0.002
  use_lars: false
  weight_decay: 0.0
  zero_init: true
