criterion:
  classes_per_batch: 15
  me_max: true
  sharpen: 0.25
  supervised_imgs_per_class: 4
  supervised_views: 1
  temperature: 0.1
  unsupervised_batch_size: 16
data:
  color_jitter_strength: 1.0
  data_seed: null
  dataset: clustervec
  image_folder: vit2019
  label_smoothing: 0.1
  multicrop: 6
  normalize: true
  root_path: /vgdata/sources/verbalisations/antai
  subset_path: /model/resnet18-2020-290-paws/reduce-balance
  unique_classes_per_rank: true
  unlabeled_frac: 0.5
logging:
  folder: /model/resnet18-2020-290-paws/reduce-balance
  write_tag: paws
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: true
  model_name: resnet50
  output_dim: 2048
  read_checkpoint: /model/checkpoints/paws_imgnt_10percent_300ep.pth.tar
  use_fp16: false
  use_pred_head: false
optimization:
  new_opt: true
  epochs: 400
  final_lr: 0.064
  lr: 6.4
  momentum: 0.9
  nesterov: false
  start_lr: 0.3
  warmup: 10
  weight_decay: 1.0e-06
